-- CREATE TABLE IF NOT EXISTS relation (
--   id INTEGER PRIMARY KEY AUTO_INCREMENT,
--   owner_id INTEGER NOT NULL,
--   target_id INTEGER NOT NULL,
--   relation_type_id INTEGER NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS relation_change (
--   id INTEGER PRIMARY KEY AUTO_INCREMENT,
--   time DATETIME NOT NULL,
--   owner_id INTEGER NOT NULL,
--   target_id INTEGER NOT NULL,
--   relation_type_id INTEGER NOT NULL,
--   is_appeared BOOLEAN NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS registered_seeker (
--   id INTEGER PRIMARY KEY AUTO_INCREMENT,
--   target_id INTEGER
-- );

-- INSERT INTO registered_seeker(id, target_id) VALUES(1, 94483676);
-- INSERT INTO registered_seeker(id, target_id) VALUES(2, 39666902);
-- INSERT INTO registered_seeker(id, target_id) VALUES(3, 57266758);

-- GENERATED BY HIBERNATE
create table if not exists registered_seeker(
	id bigint not null auto_increment primary key,
	target_id int null
);

create table if not exists relation(
	id bigint not null auto_increment primary key,
	owner_id int null,
	relation_type_id int null,
	target_id int null
);

create table if not exists relation_change(
	id bigint not null auto_increment primary key,
	is_appeared bit null,
	owner_id int null,
	relation_type_id int null,
	target_id int null,
	time tinyblob null
);